update gitflow

diff --git a/.github/workflows/student-management.yml b/.github/workflows/student-management.yml
--- a/.github/workflows/student-management.yml
+++ b/.github/workflows/student-management.yml
@@ -27,7 +27,7 @@ jobs:
           LOG_LEVEL: ${{secrets.LOG_LEVEL}}
           MONGODB_URL: ${{ secrets.MONGODB_URL }}
           NODE_ENV: ${{ secrets.NODE_ENV }}
-          PORT: ${{ secrets.3000 }}
+          PORT: ${{ secrets.PORT }}
         run: yarn jest:test
 
       - name: Build project
@@ -40,7 +40,7 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -50,15 +50,101 @@ jobs:
       - name: Install dependencies
         run: yarn install
 
-      - name: Deploy to server
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          MONGODB_URL: ${{ secrets.MONGODB_URL }}
-          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
-          NODE_ENV: ${{ secrets.NODE_ENV }}
-          PORT: ${{ secrets.PORT }}
-        run: |
-          echo "${SSH_PRIVATE_KEY}" > key.pem
-          chmod 600 key.pem
-          scp -i key.pem -o StrictHostKeyChecking=no -r ./dist user@server:/path/to/deploy
-          ssh -i key.pem -o StrictHostKeyChecking=no user@server 'pm2 restart your-app'
+     deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get the Production Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: build
+          path: applications/student/build
+
+      - name: Add SSH Key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Ensure target directory exists
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            chown ubuntu:ubuntu /home/ubuntu
+
+      - name: Copy files to EC2
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          source: "applications/student/build/*"
+          target: "/home/ubuntu/"
+
+      - name: Create .env file
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            cat <<EOF > /home/ubuntu/applications/student/build/configs/.env.production
+              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+              MONGODB_URL: ${{ secrets.MONGODB_URL }}
+              LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
+              NODE_ENV: ${{ secrets.NODE_ENV }}
+              PORT: ${{ secrets.PORT }}
+            EOF
+      - name: Start
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            #!/bin/bash
+
+            # Check if nvm is installed
+            if [ -s "$HOME/.nvm/nvm.sh" ]; then
+              source "$HOME/.nvm/nvm.sh"
+            elif [ -s "/usr/local/nvm/nvm.sh" ]; then
+              source "/usr/local/nvm/nvm.sh"
+            else
+              echo "nvm is not installed."
+              exit 1
+            fi
+
+            # Verify yarn installation
+            if ! command -v yarn &> /dev/null; then
+              echo "Yarn could not be found"
+              exit 1
+            fi
+
+            cd /home/ubuntu/applications/student/build
+            echo "Checking directory contents..."
+            ls -alh # Lists all files in the current directory
+
+            # Check if server.js exists in the correct directory
+            if [ ! -f ./src/server.js ]; then
+              echo "server.js not found in ./src/"
+              exit 1
+            fi
+
+            # Install Dependencies
+            echo "Installing dependencies..."
+            yarn install
+
+            # Check if the PM2 process is running
+            if pm2 show student > /dev/null; then
+              echo "Application is running. Restarting..."
+              yarn restart
+            else
+              echo "Application is not running. Starting..."
+              yarn start
+            fi
